spring:
  application:
    name: rendimento
  datasource:
    url: jdbc:postgresql://ep-wandering-band-agn2ylxj-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_xAE6a0OKNWDB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # oppure validate/none in produzione
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080
